public class warren2 {
    // Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
    // By starting with 1 and 2, the first 10 terms will be:
    //
    // 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    //
    // By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
    // find the sum of the even-valued terms.
    public static void main(String[] args) {
        int sum = 0;
        int j = 1;
        int x = 0;
        for(int i=2; (i+j) <= 4000000; i += x) {
            
            if( (i+j) %2 == 0) {
                sum += i+j;
            }
            x = j;
            j = i;

        }

        System.out.println(sum);
    }

}
