public class warren12 {
    // Highly Divisible Triangular Number
    //The sequence of triangle numbers is generated by adding the natural numbers.
    // So the 7th triangle number would be 1+2+3+4+5+6+7=28. THe first ten terms would be:
    // 1, 3, 6, 10, 15, 21, 28, 36, 45, 55
    // Let us list the factors of the first seven triangle numbers:
    // 1: 1
    // 3: 1, 3
    // 6: 1, 2, 3, 6
    // 10: 1, 2, 5, 10
    // 15: 1, 3, 5, 15
    // 21: 1, 3, 7, 21
    // 28: 1, 3, 4, 7, 14, 28
    // We can see the 28 is the first triangle number to have over five divisors.
    // What is the value of the first triangle number to have over five hundred divisors?

    public static void main(String[] args) {
        int tri = 0;
        int i = 0;
        int divisors = 0;
        // int[] div = new int[104];
        while(divisors < 500) {
            i++;
            tri += i;
            divisors = 0;
            for(int j = 1; j * j <= tri; j++) {
                if(tri % j == 0) {
                    divisors+= 2;
                    // div[j-1] = j;
                }
            }
        }
        // for(int j = 0; i < 100; i++) {
        //     System.out.println(div[j]);
        // }
        System.out.println(tri);
        
    }
}
